// <auto-generated />
namespace mcga.dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrating));
        
        string IMigrationMetadata.Id
        {
            get { return "202009080258306_add-rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
